name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          base-devel
          mingw-w64-i686-toolchain
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-go
    - run: |
        set MSYSTEM=MINGW64
        go build -ldflags="-extldflags=-static"
        pwd
        ls -la
    - uses: actions/upload-artifact@v2
      with:
        path: ./dialogue.exe
  mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.15.6'
      - name: Build
        run: |
          go build -o dialogue-osx
      - uses: actions/upload-artifact@v2
        with:
          path: ./dialogue-osx
  release:
    runs-on: ubuntu-latest
    needs: [win, mac]
    steps:
    - uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "MY_DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.MY_DATE }}
        release_name: Release ${{ env.MY_DATE }}
        body: |
          Latest release
        draft: false
        prerelease: false
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args:
          ./dialogue.exe
          ./dialogue-mac
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
