name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          base-devel
          mingw-w64-i686-toolchain
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-go
    - run: |
        set MSYSTEM=MINGW64
        go build -ldflags="-extldflags=-static"
        pwd
        ls -la
  mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.15.6'
      - name: Build
        run: |
          go build -o dialogue-osx
  
